SELECT * FROM-- Modelando a tabela
CREATE TABLE PESQUISASAUDE (
    UF VARCHAR(255),
    NUMERO_MUNICIPIO VARCHAR(255),
    MES_PESQUISA VARCHAR(255),
    NUMERO_ENTREVISTA INT,
    SITUACAO_MUNICIPIO VARCHAR(255),
    IDADE_MORADOR INT,
    SEXO VARCHAR(255),
    RACA_COR VARCHAR(255),
    ESCOLARIDADE VARCHAR(255),
    FEBRE VARCHAR(255),
    TOSSE VARCHAR(255),
    DOR_GARGANTA VARCHAR(255),
    DIFICULDADE_RESPIRAR VARCHAR(255),
    DOR_CABECA VARCHAR(255),
    FALTA_SABOR VARCHAR(255)
);

-- Importando os dados do arquivo CSV para a tabela PESQUISASAUDE
BULK INSERT PESQUISASAUDE
FROM 'C:\Users\trocha.ASFCORP\Downloads\covid_brasil_limpo.csv'
WITH (
    FIELDTERMINATOR = ',', 
    ROWTERMINATOR = '\n',   
    FIRSTROW = 2            
);

-- Removendo registros duplicados, mantendo o mais recente
WITH CTE AS (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY NUMERO_ENTREVISTA ORDER BY MES_PESQUISA DESC) AS rn
    FROM PESQUISASAUDE
)
DELETE FROM CTE WHERE rn > 1;

-- Corrigindo dados de idade inválidos
UPDATE PESQUISASAUDE
SET IDADE_MORADOR = NULL
WHERE IDADE_MORADOR < 0 OR IDADE_MORADOR > 120;

-- Distribuição casos por estado
SELECT UF, COUNT(*) AS Numero_de_Casos
FROM PESQUISASAUDE
GROUP BY UF
ORDER BY Numero_de_Casos DESC;

-- Análise temporal dos casos
SELECT MES_PESQUISA, COUNT(*) AS Numero_de_Casos
FROM PESQUISASAUDE
GROUP BY MES_PESQUISA
ORDER BY MES_PESQUISA;

-- Frequência de cada sintoma
SELECT 
  SUM(CASE WHEN FEBRE = 'SIM' THEN 1 ELSE 0 END) AS Casos_Com_Febre,
  SUM(CASE WHEN TOSSE = 'SIM' THEN 1 ELSE 0 END) AS Casos_Com_Tosse,
  SUM(CASE WHEN DOR_GARGANTA = 'SIM' THEN 1 ELSE 0 END) AS Casos_Com_Dor_Garganta,
  SUM(CASE WHEN DIFICULDADE_RESPIRAR = 'SIM' THEN 1 ELSE 0 END) AS Casos_Com_Dificuldade_Respirar,
  SUM(CASE WHEN DOR_CABECA = 'SIM' THEN 1 ELSE 0 END) AS Casos_Com_Dor_Cabeca,
  SUM(CASE WHEN FALTA_SABOR = 'SIM' THEN 1 ELSE 0 END) AS Casos_Com_Falta_de_Sabor
FROM PESQUISASAUDE;

-- Análise demográfica
SELECT 
  SEXO, 
  AVG(IDADE_MORADOR) AS Idade_Media,
  COUNT(*) AS Total_Casos
FROM PESQUISASAUDE
GROUP BY SEXO;

-- Correlação sintomas e demografia
SELECT 
  SEXO, 
  SUM(CASE WHEN FEBRE = 'SIM' THEN 1 ELSE 0 END) AS Casos_Com_Febre,
  AVG(IDADE_MORADOR) AS Idade_Media_Com_Febre
FROM PESQUISASAUDE
WHERE FEBRE = 'SIM'
GROUP BY SEXO;

-- Comparação por situação do município
SELECT 
  SITUACAO_MUNICIPIO, 
  COUNT(*) AS Total_Casos,
  SUM(CASE WHEN FEBRE = 'SIM' THEN 1 ELSE 0 END) AS Casos_Com_Febre
FROM PESQUISASAUDE
GROUP BY SITUACAO_MUNICIPIO;
 demo;