# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X43hJxROqFVLD2ud-deuZOirU7mvez2U
"""

import pandas as pd

# Carregar o arquivo CSV
dataframe = pd.read_csv("PNAD_COVID_112020.csv")

# Renomear as colunas com o dicionário disponibilizado pelo IBGE
dataframe.rename(columns={
    "UF": "UF",
    "V1013": "MES_PESQUISA",
    "V1016": "NUMERO_ENTREVISTA",
    "V1022": "SITUACAO_MUNICIPIO",
    "A002": "IDADE_MORADOR",
    "A003": "SEXO",
    "A004": "RACA_COR",
    "A005": "ESCOLARIDADE",
    "B0011": "FEBRE",
    "B0012": "TOSSE",
    "B0013": "DOR_GARGANTA",
    "B0014": "DIFICULDADE_RESPIRAR",
    "B0015": "DOR_CABECA",
    "B00111": "FALTA_SABOR"
}, inplace=True)

# Mapeamento de símbolos para "SIM", "NAO", "NAO SABE" e "IGNORADO"
map_sim_nao = {1: "SIM", 2: "NAO", 3: "NAO SABE", 9: "IGNORADO"}
columns_to_map = ["TOSSE", "FEBRE", "DOR_GARGANTA", "DIFICULDADE_RESPIRAR", "DOR_CABECA", "FALTA_SABOR"]
for column in columns_to_map:
    dataframe[column] = dataframe[column].map(map_sim_nao)

# Mapeamento para UF
uf_map = {31: "MINAS GERAIS", 32: "ESPIRITO SANTO", 33: "RIO DE JANEIRO", 35: "SAO PAULO"}
dataframe["UF"] = dataframe["UF"].map(uf_map)

# Mapeamento para MES_PESQUISA
mes_map = {1: "JANEIRO", 2: "FEVEREIRO", 3: "MARCO", 4: "ABRIL", 5: "MAIO", 6: "JUNHO",
           7: "JULHO", 8: "AGOSTO", 9: "SETEMBRO", 10: "OUTUBRO", 11: "NOVEMBRO", 12: "DEZEMBRO"}
dataframe["MES_PESQUISA"] = dataframe["MES_PESQUISA"].map(mes_map)

# Mapeamento para SEXO
sexo_map = {1: "HOMEM", 2: "MULHER"}
dataframe["SEXO"] = dataframe["SEXO"].map(sexo_map)

# Mapeamento para RACA_COR
raca_cor_map = {1: "BRANCA", 2: "PRETA", 3: "AMARELA", 4: "PARDA", 5: "INDIGENA", 6: "IGNORADO"}
dataframe["RACA_COR"] = dataframe["RACA_COR"].map(raca_cor_map)

# Mapeamento para ESCOLARIDADE
escolaridade_map = {1: "SEM INSTRUCAO", 2: "FUNDAMENTAL INCOMPLETO", 3: "FUNDAMENTAL COMPLETO",
                    4: "MEDIO INCOMPLETO", 5: "MEDIO COMPLETO", 6: "SUPERIOR INCOMPLETO",
                    7: "SUPERIOR COMPLETO", 8: "POS GRADUACAO"}
dataframe["ESCOLARIDADE"] = dataframe["ESCOLARIDADE"].map(escolaridade_map)

# Mapeamento para SITUACAO_MUNICIPIO
situacao_municipio_map = {1: "URBANA", 2: "RURAL"}
dataframe["SITUACAO_MUNICIPIO"] = dataframe["SITUACAO_MUNICIPIO"].map(situacao_municipio_map)

# Remove linhas onde UF é NaN (não listados no dicionário)
dataframe.dropna(subset=["UF"], inplace=True)

# Selecione as colunas renomeadas e salve o novo dataframe
dataframe = dataframe[["UF", "MES_PESQUISA", "NUMERO_ENTREVISTA", "SITUACAO_MUNICIPIO", "IDADE_MORADOR",
                       "SEXO", "RACA_COR", "ESCOLARIDADE", "FEBRE", "TOSSE", "DOR_GARGANTA",
                       "DIFICULDADE_RESPIRAR", "DOR_CABECA", "FALTA_SABOR"]]
dataframe.to_csv("covid_brasil_limpo.csv", index=False)

print(dataframe)